#
# Ubuntu Server 24.04 LTS for Raspberry Pi (arm64)
#
source_image_url=https://cdimage.ubuntu.com/releases/24.04/release

source_image_name=ubuntu-24.04.4-preinstalled-server-arm64+raspi
source_image_archive=ubuntu-24.04.4-preinstalled-server-arm64+raspi.img.xz
source_image_hash=ubuntu-24.04.4-preinstalled-server-arm64+raspi.img.xz.sha256
source_image_algo=sha256
userconf_mechanism=cloud_init
